# Generated by Django 3.0.6 on 2020-06-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expresshub', '0002_hcomment_mcomment_posth_postm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hcomment',
            name='hpost',
        ),
        migrations.RemoveField(
            model_name='hcomment',
            name='hstatus',
        ),
        migrations.RemoveField(
            model_name='mcomment',
            name='mpost',
        ),
        migrations.RemoveField(
            model_name='mcomment',
            name='mstatus',
        ),
        migrations.AddField(
            model_name='hcomment',
            name='posth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hcomments', to='expresshub.PostH'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcomment',
            name='postm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mcomments', to='expresshub.PostM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posth',
            name='statush',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Process'), (2, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='postm',
            name='statusm',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In Process'), (2, 'Completed')], default=0),
        ),
    ]
