# Generated by Django 3.0.6 on 2020-07-02 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expresshub', '0009_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.ManyToManyField(related_name='user_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
